name: Xingjun Ma
description: Xingjun Ma
menu:
 - page: About Me
   url: /about
 - page: Latest Events
   url: /events
 - page: Papers
   url: /papers
 - page: Projects
   url: /research
 - page: Curriculum Vitae
   url: /cv
 - page: Teaching
   url: /teaching
mathjax: false
markdown: kramdown
encoding: utf-8
baseurl: xingjunm.github.io
locale: en_GB
